snippets: hsc_snippets::SegmentTree< T > Class Template Reference
hsc_snippets::SegmentTree< T > Class Template Reference
#include <segment_tree.hpp>
Public Member Functions
SegmentTree (const std::vector< T > &a)
T range_sum (int left, int right)
void range_set (int left, int right, T value)
void range_add (int left, int right, T value)
int size () const
Private Member Functions
void build (const std::vector< T > &a, int s, int t, int p)
T _range_sum (int l, int r, int s, int t, int p)
void maintain (int cl, int cr, int p)
void _range_set (int l, int r, T val, int cl, int cr, int p)
void _range_add (int l, int r, T val, int cl, int cr, int p)
Private Attributes
const int n
std::vector< T > d
std::vector< T > lazy_tag
Detailed Description
template<std::integral T>
class hsc_snippets::SegmentTree< T >
Definition at line 12 of file segment_tree.hpp.
Constructor & Destructor Documentation
SegmentTree()
template<std::integral T> hsc_snippets::SegmentTree< T >::SegmentTree (const std::vector< T > & a) inline explicit
Definition at line 87 of file segment_tree.hpp.
                                                     : n(a.size())
         {
             auto vector_size = n << 2;
             d = std::vector<T>(vector_size);
             lazy_tag = std::vector<T>(vector_size, 0);
             build(a, 0, n - 1, 1);
         }
References hsc_snippets::SegmentTree< T >::build(), hsc_snippets::SegmentTree< T >::d, hsc_snippets::SegmentTree< T >::lazy_tag, and hsc_snippets::SegmentTree< T >::n.
Member Function Documentation
_range_add()
template<std::integral T> void hsc_snippets::SegmentTree< T >::_range_add (int l, int r, T val, int cl, int cr, int p) inline private
Definition at line 69 of file segment_tree.hpp.
         {
             if (l <= cl && cr <= r)
             {
                 lazy_tag[p] += val;
                 d[p] += (cr - cl + 1) * val;
                 return;
             }
             int m = cl + (cr - cl) / 2;
             maintain(cl, cr, p);
             if (l <= m)
                 _range_add(l, r, val, cl, m, p * 2);
             if (r > m)
                 _range_add(l, r, val, m + 1, cr, p * 2 + 1);
             d[p] = d[p * 2] + d[p * 2 + 1];
         }
References hsc_snippets::SegmentTree< T >::d, hsc_snippets::SegmentTree< T >::lazy_tag, and hsc_snippets::SegmentTree< T >::maintain().
Referenced by hsc_snippets::SegmentTree< T >::range_add().
_range_set()
template<std::integral T> void hsc_snippets::SegmentTree< T >::_range_set (int l, int r, T val, int cl, int cr, int p) inline private
Definition at line 53 of file segment_tree.hpp.
         {
             if (l <= cl && cr <= r)
             {
                 lazy_tag[p] = val;
                 d[p] = (cr - cl + 1) * val;
                 return;
             }
             int m = cl + (cr - cl) / 2;
             maintain(cl, cr, p);
             if (l <= m)
                 _range_set(l, r, val, cl, m, p * 2);
             if (r > m)
                 _range_set(l, r, val, m + 1, cr, p * 2 + 1);
             d[p] = d[p * 2] + d[p * 2 + 1];
         }
References hsc_snippets::SegmentTree< T >::d, hsc_snippets::SegmentTree< T >::lazy_tag, and hsc_snippets::SegmentTree< T >::maintain().
Referenced by hsc_snippets::SegmentTree< T >::range_set().
_range_sum()
template<std::integral T> T hsc_snippets::SegmentTree< T >::_range_sum (int l, int r, int s, int t, int p) inline private
Definition at line 29 of file segment_tree.hpp.
         {
             if (l <= s && t <= r)
                 return d[p];
             int m = s + ((t - s) >> 1), sum = 0;
             maintain(s, t, p);
             if (l <= m)
                 sum += _range_sum(l, r, s, m, p * 2);
             if (r > m)
                 sum += _range_sum(l, r, m + 1, t, p * 2 + 1);
             return sum;
         }
References hsc_snippets::SegmentTree< T >::d, hsc_snippets::SegmentTree< T >::maintain(), and hsc_snippets::sum().
Referenced by hsc_snippets::SegmentTree< T >::range_sum().
build()
template<std::integral T> void hsc_snippets::SegmentTree< T >::build (const std::vector< T > & a, int s, int t, int p) inline private
Definition at line 18 of file segment_tree.hpp.
         {
             if (s == t)
             {
                 d[p] = a[s];
                 return;
             }
             int m = s + ((t - s) >> 1);
             build(a, s, m, p * 2), build(a, m + 1, t, p * 2 + 1);
             d[p] = d[p * 2] + d[(p * 2) + 1];
         }
References hsc_snippets::SegmentTree< T >::d.
Referenced by hsc_snippets::SegmentTree< T >::SegmentTree().
maintain()
template<std::integral T> void hsc_snippets::SegmentTree< T >::maintain (int cl, int cr, int p) inline private
Definition at line 41 of file segment_tree.hpp.
         {
             int cm = cl + (cr - cl) / 2;
             if (cl != cr && lazy_tag[p])
             {
                 lazy_tag[p * 2] += lazy_tag[p];
                 lazy_tag[p * 2 + 1] += lazy_tag[p];
                 d[p * 2] += lazy_tag[p] * (cm - cl + 1);
                 d[p * 2 + 1] += lazy_tag[p] * (cr - cm);
                 lazy_tag[p] = 0;
             }
         }
References hsc_snippets::SegmentTree< T >::d, and hsc_snippets::SegmentTree< T >::lazy_tag.
Referenced by hsc_snippets::SegmentTree< T >::_range_add(), hsc_snippets::SegmentTree< T >::_range_set(), and hsc_snippets::SegmentTree< T >::_range_sum().
range_add()
template<std::integral T> void hsc_snippets::SegmentTree< T >::range_add (int left, int right, T value) inline
Add value to all elements in the range [left, right].
Parameters
left 0-indexed, inclusive
right 0-indexed, inclusive
value The value to add for each element within the specified range
Definition at line 118 of file segment_tree.hpp.
 { _range_add(left, right, value, 0, n - 1, 1); }
References hsc_snippets::SegmentTree< T >::_range_add(), and hsc_snippets::SegmentTree< T >::n.
range_set()
template<std::integral T> void hsc_snippets::SegmentTree< T >::range_set (int left, int right, T value) inline
Assign value to all elements in the range [left, right].
Parameters
left 0-indexed, inclusive
right 0-indexed, inclusive
value The value to set for each element within the specified range
Definition at line 110 of file segment_tree.hpp.
 { _range_set(left, right, value, 0, n - 1, 1); }
References hsc_snippets::SegmentTree< T >::_range_set(), and hsc_snippets::SegmentTree< T >::n.
range_sum()
template<std::integral T> T hsc_snippets::SegmentTree< T >::range_sum (int left, int right) inline
Compute the sum of values within the range [left, right].
Parameters
left 0-indexed, inclusive
right 0-indexed, inclusive
Definition at line 99 of file segment_tree.hpp.
         {
             return _range_sum(left, right, 0, n - 1, 1);
         }
References hsc_snippets::SegmentTree< T >::_range_sum(), and hsc_snippets::SegmentTree< T >::n.
size()
template<std::integral T> int hsc_snippets::SegmentTree< T >::size () const inline
Return the size of the original vector.
Definition at line 123 of file segment_tree.hpp.
 { return n; }
References hsc_snippets::SegmentTree< T >::n.
Field Documentation
d
template<std::integral T> std::vector<T> hsc_snippets::SegmentTree< T >::d private
Definition at line 16 of file segment_tree.hpp.
Referenced by hsc_snippets::SegmentTree< T >::_range_add(), hsc_snippets::SegmentTree< T >::_range_set(), hsc_snippets::SegmentTree< T >::_range_sum(), hsc_snippets::SegmentTree< T >::build(), hsc_snippets::SegmentTree< T >::maintain(), and hsc_snippets::SegmentTree< T >::SegmentTree().
lazy_tag
template<std::integral T> std::vector<T> hsc_snippets::SegmentTree< T >::lazy_tag private
Definition at line 17 of file segment_tree.hpp.
Referenced by hsc_snippets::SegmentTree< T >::_range_add(), hsc_snippets::SegmentTree< T >::_range_set(), hsc_snippets::SegmentTree< T >::maintain(), and hsc_snippets::SegmentTree< T >::SegmentTree().
n
template<std::integral T> const int hsc_snippets::SegmentTree< T >::n private
Definition at line 15 of file segment_tree.hpp.
Referenced by hsc_snippets::SegmentTree< T >::range_add(), hsc_snippets::SegmentTree< T >::range_set(), hsc_snippets::SegmentTree< T >::range_sum(), hsc_snippets::SegmentTree< T >::SegmentTree(), and hsc_snippets::SegmentTree< T >::size().
The documentation for this class was generated from the following file:
src/segment_tree.hpp