snippets: hsc_snippets Namespace Reference
hsc_snippets Namespace Reference
Data Structures
struct TreeNode
class DominantTracker
struct _Interval
struct Override
struct Maximum
class IntervalMap
class MonotonicStack
class SegmentTree
class SlidingWindowMax
class UnionFind
Typedefs
template<typename T >
using MonotonicDecreasingStack = MonotonicStack< T, std::less_equal< T > >
template<typename T >
using MonotonicIncreasingStack = MonotonicStack< T, std::greater_equal< T > >
Functions
TreeNode * new_binary_tree (const std::vector< std::optional< int >> v)
void delete_binary_tree (TreeNode *root)
int get_binary_tree_depth (TreeNode *root)
void inorder (TreeNode *root, std::function< void(int)> func)
void preorder (TreeNode *root, std::function< void(int)> func)
void postorder (TreeNode *root, std::function< void(int)> func)
std::unordered_map< int, std::vector< int > > binary_tree_to_adjacency_list (TreeNode *root)
std::vector< std::vector< std::pair< int, int > > > make_weighted_directed_adjacency_list (int n, const std::vector< std::vector< int >> &edges)
std::vector< std::vector< int > > make_unweighted_undirected_adjacency_list (int n, const std::vector< std::vector< int >> &edges)
std::vector< std::vector< std::pair< int, int > > > make_weighted_undirected_adjacency_list (int n, const std::vector< std::vector< int >> &edges)
std::vector< std::vector< int > > make_unweighted_directed_adjacency_list (int n, const std::vector< std::vector< int >> &edges)
void breadth_first_search (std::vector< std::vector< int >> &adjacency_list, int root, std::function< void(int, int)> callback)
void breadth_first_search (std::unordered_map< int, std::vector< int >> &adjacency_list, int root, std::function< void(int, int)> callback)
void depth_first_search (std::vector< std::vector< int >> &adjacency_list, int root, std::function< void(int, int)> callback)
int dijkstra (int n, const std::vector< std::vector< std::pair< int, int >>> &adjacency_list, int src, int dst)
std::vector< int > find_euler_path_directed (const std::vector< std::vector< int >> &edges)
std::vector< std::vector< int > > findConnectedComponents (std::unordered_map< int, std::vector< int >> &adj)
template<std::integral T>
static bool operator< (const _Interval< T > &interval, T x)
template<std::integral T>
static bool operator< (T x, const _Interval< T > &interval)
template<std::integral T>
static bool operator< (const _Interval< T > &interval1, const _Interval< T > &interval2)
constexpr int modular_add (int x, int y)
constexpr int additive_inverse (int x)
constexpr int modular_substract (int x, int y)
constexpr int modular_multiply (int x, int y)
constexpr int modular_square (int x)
constexpr int modular_cube (int x)
int modular_pow2 (size_t exponent)
template<typename T >
std::vector< T > nextGreaterElement (const std::vector< T > &nums, std::function< T()> no_greater)
template<std::integral T>
int numDigits (T num)
template<std::integral T>
int numBits (T num)
template<std::integral T>
T gcd (T a, T b)
template<std::integral T>
T lcm (T a, T b)
std::vector< int > SieveOfEratosthenes (int n)
template<std::totally_ordered T>
int numOfGreaterElements (const std::vector< T > &v, T value)
template<std::integral T>
bool containsInRange (const std::vector< T > &vec, T start, T end)
template<typename T , std::integral I = int>
std::optional< I > binary_search (I low, I high, const T &value, auto &&func)
template<typename T , std::integral I = int>
I greatest_index (I low, I high, const T &value, auto &&func)
template<typename T , std::integral I = int>
I smallest_index (I low, I high, const T &value, auto &&func)
template<std::integral T>
void sortThree (T &a, T &b, T &c)
std::vector< int > kmpSearch (const std::string &pat, const std::string &txt)
bool isPalindrome (const std::string &s)
template<std::integral T>
std::string to_string (const std::vector< T > &vec)
std::string to_string (const std::vector< std::string > &vec)
template<std::integral T>
std::string to_string (const std::vector< std::vector< T >> &vec)
template<numeric T>
bool lessThanAll (T x, T val)
template<numeric T, numeric... Args>
bool lessThanAll (T x, T val, Args... args)
template<numeric T>
bool lessThanOrEqualToAll (T x, T val)
template<numeric T, numeric... Args>
bool lessThanOrEqualToAll (T x, T val, Args... args)
template<numeric T>
bool greaterThanAll (T x, T val)
template<numeric T, numeric... Args>
bool greaterThanAll (T x, T val, Args... args)
template<numeric T>
bool greaterThanOrEqualToAll (T x, T val)
template<numeric T, numeric... Args>
bool greaterThanOrEqualToAll (T x, T val, Args... args)
template<numeric T>
T sum (T x)
template<numeric T, numeric... Args>
T sum (T x, Args... args)
Variables
static constexpr int MODULO = static_cast<int>(1e9 + 7)
template<typename T >
concept numeric = std::integral<T> || std::floating_point<T>
Typedef Documentation
MonotonicDecreasingStack
template<typename T > using hsc_snippets::MonotonicDecreasingStack = typedef MonotonicStack<T, std::less_equal<T> >
Definition at line 66 of file monotonic_stack.hpp.
MonotonicIncreasingStack
template<typename T > using hsc_snippets::MonotonicIncreasingStack = typedef MonotonicStack<T, std::greater_equal<T> >
Definition at line 68 of file monotonic_stack.hpp.
Function Documentation
additive_inverse()
constexpr int hsc_snippets::additive_inverse (int x) constexpr
Definition at line 20 of file modular_arithmetic.hpp.
     {
         x = x % MODULO; // x might be negative
         x = (x + MODULO) % MODULO;
         return MODULO - x;
     }
References MODULO.
binary_search()
template<typename T , std::integral I = int> std::optional<I> hsc_snippets::binary_search (I low, I high, const T & value, auto && func)
Definition at line 45 of file sorted_utils.hpp.
     {
         while (low <= high)
         {
             I mid = low + (high - low) / 2;
             T res = func(mid);
             if (res == value)
             {
                 return mid;
             }
             else if (res < value)
             {
                 low = mid + 1;
             }
             else
             {
                 high = mid - 1;
             }
         }
         return std::nullopt;
     }
binary_tree_to_adjacency_list()
std::unordered_map<int, std::vector<int> > hsc_snippets::binary_tree_to_adjacency_list (TreeNode * root)
Converts a binary tree to an adjacency list representation. All node values in the binary tree must be unique. The adjacency list is bidirectional, meaning for each parent-child relation, both the parent's list contains the child and the child's list contains the parent.
Parameters
root A pointer to the root node of the binary tree. If the tree is empty (nullptr), the function returns an empty adjacency list.
Returns
An unordered_map where keys are node values and values are vectors of integers representing the node values of adjacent nodes.
Definition at line 158 of file binary_tree.hpp.
     {
         auto adjacencyList = std::unordered_map<int, std::vector<int>>{};
         if (root == nullptr)
         {
             return adjacencyList;
         }
         auto q = std::queue<TreeNode *>{};
         q.push(root);
         while (!q.empty())
         {
             auto node = q.front();
             q.pop();
             if (node->left != nullptr)
             {
                 adjacencyList[node->left->val].push_back(node->val);
                 adjacencyList[node->val].push_back(node->left->val);
                 q.push(node->left);
             }
             if (node->right != nullptr)
             {
                 adjacencyList[node->right->val].push_back(node->val);
                 adjacencyList[node->val].push_back(node->right->val);
                 q.push(node->right);
             }
         }
         return adjacencyList;
     }
breadth_first_search() [1/2]
void hsc_snippets::breadth_first_search (std::unordered_map< int, std::vector< int >> & adjacency_list, int root, std::function< void(int, int)> callback)
Performs a breadth-first search (BFS) on an undirected graph starting from a given root node. It uses a queue to explore nodes level by level, ensuring each node is visited exactly once.
Parameters
adjacency_list The graph represented as an adjacency list, where each key-value pair corresponds to a node and its list of adjacent nodes.
root The starting node for the BFS.
callback A function to be called for each visited node. It takes the distance from the root and the node itself as arguments.
Definition at line 164 of file graph.hpp.
     {
         auto visited = std::unordered_set<int>{};
         auto q = std::queue<std::pair<int, int>>{}; // Regular queue for BFS
         q.emplace(0, root);                         // Initialize queue with root node at distance 0
         while (!q.empty())
         {
             auto [dist, node] = q.front(); // Extract node at the front of the queue
             q.pop();
             if (visited.contains(node)) // Skip if node has already been visited
             {
                 continue;
             }
             visited.insert(node); // Mark current node as visited
             callback(dist, node); // Invoke callback for the current node
             for (auto adjacent_node : adjacency_list[node]) // Explore adjacent nodes
             {
                 if (visited.contains(adjacent_node)) // Skip if adjacent node has already been visited
                 {
                     continue;
                 }
                 q.emplace(dist + 1, adjacent_node); // Enqueue adjacent node with distance incremented by 1
             }
         }
     }
breadth_first_search() [2/2]
void hsc_snippets::breadth_first_search (std::vector< std::vector< int >> & adjacency_list, int root, std::function< void(int, int)> callback)
Performs a breadth-first search (BFS) traversal on a graph represented by an adjacency list, starting from the specified root node.
Parameters
adjacency_list The adjacency list representation of the graph. Each element represents a node and contains the indices of its adjacent nodes.
root The index of the root node from which the BFS traversal starts.
callback A callback function invoked for each visited node during the BFS traversal. It takes two parameters: the distance of the current node from the root and the index of the current node.
Definition at line 126 of file graph.hpp.
     {
         auto visited = std::unordered_set<int>{};
         auto q = std::queue<std::pair<int, int>>{}; // Regular queue for BFS
         q.emplace(0, root);                         // Initialize queue with root node at distance 0
         while (!q.empty())
         {
             auto [dist, node] = q.front(); // Extract node at the front of the queue
             q.pop();
             if (visited.contains(node)) // Skip if node has already been visited
             {
                 continue;
             }
             visited.insert(node); // Mark current node as visited
             callback(dist, node); // Invoke callback for the current node
             for (auto adjacent_node : adjacency_list[node]) // Explore adjacent nodes
             {
                 if (visited.contains(adjacent_node)) // Skip if adjacent node has already been visited
                 {
                     continue;
                 }
                 q.emplace(dist + 1, adjacent_node); // Enqueue adjacent node with distance incremented by 1
             }
         }
     }
Referenced by findConnectedComponents().
containsInRange()
template<std::integral T> bool hsc_snippets::containsInRange (const std::vector< T > & vec, T start, T end)
Definition at line 24 of file sorted_utils.hpp.
     {
         if (vec.empty() || start >= end)
         {
             return false;
         }
         // Lower bound of the range
         auto lower = std::lower_bound(vec.begin(), vec.end(), start);
         // Check if the lower bound is not beyond the vector and less than 'end'
         if (lower != vec.end() && *lower < end)
         {
             return true;
         }
         return false;
     }
delete_binary_tree()
void hsc_snippets::delete_binary_tree (TreeNode * root)
Deletes all nodes of a binary tree to free memory.
Parameters
root A pointer to the root node of the binary tree. If the pointer is nullptr, the function does nothing, safely handling the case of an empty tree or reaching the end of a branch.
Definition at line 79 of file binary_tree.hpp.
     {
         if (root == nullptr)
             return;
         delete_binary_tree(root->left);
         delete_binary_tree(root->right);
         delete root;
     }
References hsc_snippets::TreeNode::left, and hsc_snippets::TreeNode::right.
depth_first_search()
void hsc_snippets::depth_first_search (std::vector< std::vector< int >> & adjacency_list, int root, std::function< void(int, int)> callback)
Performs a depth-first search (DFS) traversal on a graph represented by an adjacency list, starting from the specified root node.
Parameters
adjacency_list The adjacency list representation of the graph. Each element represents a node and contains the indices of its adjacent nodes.
root The index of the root node from which the DFS traversal starts.
callback A callback function invoked for each visited node during the DFS traversal. It takes two parameters: the distance of the current node from the root and the index of the current node.
Definition at line 204 of file graph.hpp.
     {
         auto visited = std::unordered_set<int>{};
         auto stack = std::stack<std::pair<int, int>>{}; // Stack for DFS
         stack.emplace(0, root);                         // Initialize stack with root node at distance 0
         while (!stack.empty())
         {
             auto [dist, node] = stack.top(); // Extract node at the top of the stack
             stack.pop();
             if (visited.contains(node)) // Skip if node has already been visited
             {
                 continue;
             }
             visited.insert(node); // Mark current node as visited
             callback(dist, node); // Invoke callback for the current node
             for (auto adjacent_node : adjacency_list[node]) // Explore adjacent nodes
             {
                 if (visited.contains(adjacent_node)) // Skip if adjacent node has already been visited
                 {
                     continue;
                 }
                 stack.emplace(dist + 1, adjacent_node); // Push adjacent node with distance incremented by 1
             }
         }
     }
dijkstra()
int hsc_snippets::dijkstra (int n, const std::vector< std::vector< std::pair< int, int >>> & adjacency_list, int src, int dst)
Dijkstra's algorithm to find the shortest path from source to destination in a graph.
Parameters
n Number of vertices in the graph.
adjacency_list Adjacency list representation of the graph where each element is a pair representing an edge (to, weight).
src Source vertex.
dst Destination vertex.
Returns
Shortest distance from source to destination. Returns -1 if no path exists.
Definition at line 242 of file graph.hpp.
     {
         std::vector<int> dist(n, std::numeric_limits<int>::max());
         std::priority_queue<std::pair<int, int>, std::vector<std::pair<int, int>>, std::greater<>> pq;
         dist[src] = 0;
         pq.emplace(0, src);
         while (!pq.empty())
         {
             int u = pq.top().second;
             pq.pop();
             for (const auto &neighbor : adjacency_list[u])
             {
                 int v = neighbor.first;
                 int weight = neighbor.second;
                 if (dist[v] > dist[u] + weight)
                 {
                     dist[v] = dist[u] + weight;
                     pq.emplace(dist[v], v);
                 }
             }
         }
         return dist[dst] == std::numeric_limits<int>::max() ? -1 : dist[dst];
     }
find_euler_path_directed()
std::vector<int> hsc_snippets::find_euler_path_directed (const std::vector< std::vector< int >> & edges)
Finds an Eulerian path or circuit in a directed graph.
This function assumes that the given graph has an Eulerian path or circuit, which means the graph is connected and either:
All vertices have equal in-degrees and out-degrees (Eulerian circuit), or
All but two vertices have equal in-degrees and out-degrees, and one of those two vertices has out-degree = in-degree + 1 (start), and the other has in-degree = out-degree + 1 (end) (Eulerian path).
Parameters
edges A vector of pairs representing directed edges in the graph. Each pair (a, b) represents a directed edge from a to b.
Returns
A vector representing the Eulerian path or circuit as a sequence of vertex indices. If a circuit exists, the path can start from any vertex in the circuit.
Definition at line 289 of file graph.hpp.
     {
         std::unordered_map<int, std::stack<int>> adj;
         std::unordered_map<int, int> in;
         std::unordered_map<int, int> out;
         for (auto &&edge : edges)
         {
             int from = edge[0];
             int to = edge[1];
             adj[from].push(to);
             in[to] += 1;
             out[from] += 1;
         }
         int start = adj.begin()->first; // Default start node
         for (auto &&p : adj)
         {
             if (out[p.first] - in[p.first] == 1)
             { // Find the actual start node for Euler Path
                 start = p.first;
                 break;
             }
         }
         std::stack<int> current_path;
         std::vector<int> circuit;
         current_path.push(start);
         while (!current_path.empty())
         {
             int current_vertex = current_path.top();
             if (!adj[current_vertex].empty())
             { // If current vertex has neighbors
                 int next_vertex = adj[current_vertex].top();
                 adj[current_vertex].pop();      // Remove the edge from current to next
                 current_path.push(next_vertex); // Move to next vertex
             }
             else
             {                                      // Backtrack
                 circuit.push_back(current_vertex); // Add to Euler circuit/path
                 current_path.pop();                // Remove the vertex as it has no more neighbors
             }
         }
         // Reverse the circuit to get the Euler path
         std::reverse(circuit.begin(), circuit.end());
         return circuit;
     }
findConnectedComponents()
std::vector<std::vector<int> > hsc_snippets::findConnectedComponents (std::unordered_map< int, std::vector< int >> & adj)
Finds and returns all connected components in an undirected graph. It iterates over all nodes, using a BFS starting from each unvisited node to discover all nodes in the same connected component.
Parameters
adj The graph represented as an adjacency list, where keys are node identifiers and values are lists of adjacent nodes.
Returns
A vector of vectors, where each inner vector represents a connected component of the graph and contains all node identifiers within that component.
Definition at line 350 of file graph.hpp.
     {
         std::unordered_map<int, bool> visited{}; // Tracks whether each node has been visited
         for (auto &&p : adj)
         {
             visited.insert({p.first, false}); // Initialize all nodes as unvisited
         }
         std::vector<std::vector<int>> connectedComponents; // Stores the connected components
         for (auto &&p : visited)
         {
             if (!p.second)
             {                               // For each unvisited node
                 std::vector<int> component; // Stores the current component's nodes
                 breadth_first_search(adj, p.first, [&visited, &component](int, int node)
{
                                          visited[node] = true;      // Mark the node as visited
                                          component.push_back(node); // Add the node to the current component
                                      });                            // Perform BFS to find all nodes in this component
                 connectedComponents.push_back(component);           // Add the current component to the list
             }
         }
         return connectedComponents; // Return all found connected components
     }
References breadth_first_search().
gcd()
template<std::integral T> T hsc_snippets::gcd (T a, T b)
Calculates the greatest common divisor (GCD) of two numbers using the Euclidean algorithm.
Template Parameters
T A numeric type that should be an integral type (e.g., int, long).
Parameters
a The first number.
b The second number.
Returns
The greatest common divisor of a and b.
Definition at line 63 of file number_utils.hpp.
     {
         while (b != 0)
         {
             T temp = b;
             b = a % b;
             a = temp;
         }
         return a; // When b becomes 0, a contains the gcd
     }
Referenced by lcm().
get_binary_tree_depth()
int hsc_snippets::get_binary_tree_depth (TreeNode * root)
Calculates the depth of a binary tree.
Parameters
root A pointer to the root node of the binary tree. If the tree is empty (nullptr), the depth is considered to be 0.
Returns
The depth of the binary tree as an integer. An empty tree has a depth of 0.
Definition at line 95 of file binary_tree.hpp.
     {
         if (root == nullptr)
             return 0;
         int depth = 1;
         depth = std::max(depth, get_binary_tree_depth(root->left) + 1);
         depth = std::max(depth, get_binary_tree_depth(root->right) + 1);
         return depth;
     }
References hsc_snippets::TreeNode::left, and hsc_snippets::TreeNode::right.
greaterThanAll() [1/2]
template<numeric T> bool hsc_snippets::greaterThanAll (T x, T val)
Definition at line 38 of file varadic_numeric.hpp.
     {
         return x > val;
     }
Referenced by greaterThanAll().
greaterThanAll() [2/2]
template<numeric T, numeric... Args> bool hsc_snippets::greaterThanAll (T x, T val, Args... args)
Definition at line 43 of file varadic_numeric.hpp.
     {
         if (!(x > val))
             return false;
         return greaterThanAll(x, args...);
     }
References greaterThanAll().
greaterThanOrEqualToAll() [1/2]
template<numeric T> bool hsc_snippets::greaterThanOrEqualToAll (T x, T val)
Definition at line 51 of file varadic_numeric.hpp.
     {
         return x >= val;
     }
Referenced by greaterThanOrEqualToAll().
greaterThanOrEqualToAll() [2/2]
template<numeric T, numeric... Args> bool hsc_snippets::greaterThanOrEqualToAll (T x, T val, Args... args)
Definition at line 56 of file varadic_numeric.hpp.
     {
         if (!(x >= val))
             return false;
         return greaterThanOrEqualToAll(x, args...);
     }
References greaterThanOrEqualToAll().
greatest_index()
template<typename T , std::integral I = int> I hsc_snippets::greatest_index (I low, I high, const T & value, auto && func)
Finds the greatest index in a non-decreasing array where the function applied to the index returns a value less than or equal to the specified value.
Template Parameters
T The type of the value against which the function's results are compared.
I The integral type of the index, defaulting to int.
Parameters
low The lower bound of the search range (inclusive).
high The upper bound of the search range (inclusive).
value The value to compare against the function's results.
func The function to apply to each index, expected to return non-decreasing values for the range [low, high].
Returns
The greatest index for which func(index) <= value, or -1 if no such index exists.
Definition at line 85 of file sorted_utils.hpp.
     {
         I ans = -1; // Initialize answer to -1 to indicate no valid index found yet
         while (low <= high)
         {
             I mid = low + (high - low) / 2; // Calculate the mid-point of the current search range
             T res = func(mid);              // Evaluate the function at the mid-point
             if (res <= value)
             {
                 ans = mid;     // Update answer since res is less than or equal to value
                 low = mid + 1; // Narrow the search to the right half to find the greatest index
             }
             else
             {
                 high = mid - 1; // Narrow the search to the left half since res is greater than value
             }
         }
         return ans; // Return the found index or -1 if no such index exists
     }
inorder()
void hsc_snippets::inorder (TreeNode * root, std::function< void(int)> func)
In-order traversal of a binary tree.
Parameters
root Root node of the binary tree.
func Function to process each node's value.
Definition at line 110 of file binary_tree.hpp.
     {
         if (root == nullptr)
             return;
         inorder(root->left, func);
         func(root->val);
         inorder(root->right, func);
     }
References hsc_snippets::TreeNode::left, hsc_snippets::TreeNode::right, and hsc_snippets::TreeNode::val.
isPalindrome()
bool hsc_snippets::isPalindrome (const std::string & s)
Checks if a given string is a palindrome.
Parameters
s The string to check for palindromicity.
Returns
True if 's' is a palindrome, False otherwise.
Definition at line 97 of file string_utils.hpp.
     {
         assert(!s.empty());
         const int n = s.size();
         for (int i = 0; i < n / 2; i++)
         {
             if (s[i] != s[n - 1 - i])
             {
                 return false;
             }
         }
         return true;
     }
kmpSearch()
std::vector<int> hsc_snippets::kmpSearch (const std::string & pat, const std::string & txt)
Searches for all occurrences of a pattern within a text using the Knuth-Morris-Pratt (KMP) algorithm.
The KMP algorithm pre-processes the pattern to construct an array of longest proper prefixes which are also suffixes (LPS array). It then uses this LPS array to skip redundant comparisons when a mismatch occurs, thereby improving the search efficiency.
Parameters
pat The pattern string to search for within the text.
txt The text string in which to search for the pattern.
Returns
A vector containing the starting indices of all occurrences of 'pat' within 'txt'.
Definition at line 24 of file string_utils.hpp.
     {
         int M = pat.size();
         int N = txt.size();
         // Longest Prefix Suffix (lps) array
         std::vector<int> lps(M);
         std::vector<int> result;
         // Preprocess the pattern
         int len = 0;
         lps[0] = 0; // lps[0] is always 0
         int i = 1;
         while (i < M)
         {
             if (pat[i] == pat[len])
             {
                 len++;
                 lps[i] = len;
                 i++;
             }
             else
             {
                 if (len != 0)
                 {
                     len = lps[len - 1];
                 }
                 else
                 {
                     lps[i] = 0;
                     i++;
                 }
             }
         }
         // Search the pattern in txt
         i = 0;     // index for txt[]
         int j = 0; // index for pat[]
         while (i < N)
         {
             if (pat[j] == txt[i])
             {
                 j++;
                 i++;
             }
             if (j == M)
             {
                 result.push_back(i - j);
                 j = lps[j - 1];
             }
             else if (i < N && pat[j] != txt[i])
             {
                 if (j != 0)
                 {
                     j = lps[j - 1];
                 }
                 else
                 {
                     i = i + 1;
                 }
             }
         }
         return result;
     }
lcm()
template<std::integral T> T hsc_snippets::lcm (T a, T b)
Calculates the least common multiple (LCM) of two numbers using the formula: LCM(a, b) = (a * b) / GCD(a, b)
Template Parameters
T A numeric type that should be an integral type (e.g., int, long).
Parameters
a The first number.
b The second number.
Returns
The least common multiple of a and b.
Definition at line 84 of file number_utils.hpp.
     {
         return (a * b) / gcd(a, b);
     }
References gcd().
lessThanAll() [1/2]
template<numeric T> bool hsc_snippets::lessThanAll (T x, T val)
Definition at line 12 of file varadic_numeric.hpp.
     {
         return x < val;
     }
Referenced by lessThanAll().
lessThanAll() [2/2]
template<numeric T, numeric... Args> bool hsc_snippets::lessThanAll (T x, T val, Args... args)
Definition at line 17 of file varadic_numeric.hpp.
     {
         if (!(x < val))
             return false;
         return lessThanAll(x, args...);
     }
References lessThanAll().
lessThanOrEqualToAll() [1/2]
template<numeric T> bool hsc_snippets::lessThanOrEqualToAll (T x, T val)
Definition at line 25 of file varadic_numeric.hpp.
     {
         return x <= val;
     }
Referenced by lessThanOrEqualToAll().
lessThanOrEqualToAll() [2/2]
template<numeric T, numeric... Args> bool hsc_snippets::lessThanOrEqualToAll (T x, T val, Args... args)
Definition at line 30 of file varadic_numeric.hpp.
     {
         if (!(x <= val))
             return false;
         return lessThanOrEqualToAll(x, args...);
     }
References lessThanOrEqualToAll().
make_unweighted_directed_adjacency_list()
std::vector<std::vector<int> > hsc_snippets::make_unweighted_directed_adjacency_list (int n, const std::vector< std::vector< int >> & edges)
Constructs an unweighted, directed adjacency list representation of a graph from a given set of edges. Nodes are indexed from 0 to n-1.
Parameters
n The number of nodes in the graph.
edges A vector of vectors representing edges, where each inner vector contains two integers: [from, to], denoting a directed edge from node 'from' to node 'to'.
Returns
A vector of vectors representing the adjacency list of the graph. Each inner vector corresponds to a node, containing the indices of connected nodes (edges are unweighted in this representation).
Definition at line 103 of file graph.hpp.
     {
         auto adjacency_list = std::vector<std::vector<int>>(n);
         for (auto &&edge : edges)
         {
             int from = edge[0];
             int to = edge[1];
             adjacency_list[from].push_back(to);
         }
         return adjacency_list;
     }
make_unweighted_undirected_adjacency_list()
std::vector<std::vector<int> > hsc_snippets::make_unweighted_undirected_adjacency_list (int n, const std::vector< std::vector< int >> & edges)
Constructs an unweighted, undirected adjacency list representation of a graph from a given set of edges. Nodes are indexed from 0 to n-1.
Parameters
n The number of nodes in the graph.
edges A vector of vectors representing edges, where each inner vector contains two integers: [from, to], denoting an edge from node 'from' to node 'to'.
Returns
A vector of vectors representing the adjacency list of the graph. Each inner vector corresponds to a node, containing the indices of connected nodes (edges are unweighted in this representation).
Definition at line 52 of file graph.hpp.
     {
         auto adjacency_list = std::vector<std::vector<int>>(n);
         for (auto &&edge : edges)
         {
             int from = edge[0];
             int to = edge[1];
             adjacency_list[from].push_back(to);
             adjacency_list[to].push_back(from); // For undirected graph, edges are bidirectional
         }
         return adjacency_list;
     }
make_weighted_directed_adjacency_list()
std::vector<std::vector<std::pair<int, int> > > hsc_snippets::make_weighted_directed_adjacency_list (int n, const std::vector< std::vector< int >> & edges)
Constructs a weighted, directed adjacency list representation of a graph from a given set of edges. Nodes are indexed from 0 to n-1.
Parameters
n The number of nodes in the graph.
edges A vector of vectors representing edges, where each inner vector contains three integers: [from, to, weight], denoting a weighted edge from node 'from' to node 'to' with the given weight.
Returns
A vector of vectors of pairs representing the adjacency list of the graph. Each inner vector corresponds to a node, containing pairs of connected nodes and their respective edge weights.
Definition at line 27 of file graph.hpp.
     {
         auto adjacency_list = std::vector<std::vector<std::pair<int, int>>>(n);
         for (auto &&edge : edges)
         {
             int from = edge[0];
             int to = edge[1];
             int weight = edge[2];
             adjacency_list[from].emplace_back(to, weight);
         }
         return adjacency_list;
     }
make_weighted_undirected_adjacency_list()
std::vector<std::vector<std::pair<int, int> > > hsc_snippets::make_weighted_undirected_adjacency_list (int n, const std::vector< std::vector< int >> & edges)
Constructs a weighted, undirected adjacency list representation of a graph from a given set of edges. Nodes are indexed from 0 to n-1.
Parameters
n The number of nodes in the graph.
edges A vector of vectors representing edges, where each inner vector contains three integers: [from, to, weight], denoting a weighted edge between node 'from' and node 'to' with the given weight.
Returns
A vector of vectors of pairs representing the adjacency list of the graph. Each inner vector corresponds to a node, containing pairs of connected nodes and their respective edge weights.
Definition at line 77 of file graph.hpp.
     {
         auto adjacency_list = std::vector<std::vector<std::pair<int, int>>>(n);
         for (auto &&edge : edges)
         {
             int from = edge[0];
             int to = edge[1];
             int weight = edge[2];
             adjacency_list[from].emplace_back(to, weight);
             adjacency_list[to].emplace_back(from, weight); // For undirected graph, edges are bidirectional
         }
         return adjacency_list;
     }
modular_add()
constexpr int hsc_snippets::modular_add (int x, int y) constexpr
Definition at line 12 of file modular_arithmetic.hpp.
     {
         auto a = static_cast<std::int64_t>(x);
         auto b = static_cast<std::int64_t>(y);
         auto c = (a + b) % MODULO;
         return static_cast<int>(c);
     }
References MODULO.
modular_cube()
constexpr int hsc_snippets::modular_cube (int x) constexpr
Definition at line 52 of file modular_arithmetic.hpp.
     {
         auto a = static_cast<int64_t>(x);
         auto b = (a * a) % MODULO;
         auto c = (b * a) % MODULO;
         return static_cast<int>(c);
     }
References MODULO.
modular_multiply()
constexpr int hsc_snippets::modular_multiply (int x, int y) constexpr
Definition at line 37 of file modular_arithmetic.hpp.
     {
         auto a = static_cast<std::int64_t>(x);
         auto b = static_cast<std::int64_t>(y);
         auto c = (a * b) % MODULO;
         return static_cast<int>(c);
     }
References MODULO.
modular_pow2()
int hsc_snippets::modular_pow2 (size_t exponent)
Definition at line 61 of file modular_arithmetic.hpp.
     {
         constexpr size_t N = 25;
         constexpr auto lookup{[]() constexpr
{
                                   std::array<int, N> a{};
                                   a[0] = 1;
                                   for (size_t i = 1; i < N; i++)
{
                                       a[i] = a[i - 1] << 1;
                                   }
                                   return a;
                               }()};
         if (exponent <= N)
         {
             return lookup[exponent] % MODULO;
         }
         auto half_e = exponent >> 1;
         auto tmp = static_cast<std::int64_t>(modular_pow2(half_e));
         auto m = (exponent & 1);
         return ((tmp * tmp) << m) % MODULO;
     }
References MODULO.
modular_square()
constexpr int hsc_snippets::modular_square (int x) constexpr
Definition at line 45 of file modular_arithmetic.hpp.
     {
         auto a = static_cast<int64_t>(x);
         auto b = (a * a) % MODULO;
         return static_cast<int>(b);
     }
References MODULO.
modular_substract()
constexpr int hsc_snippets::modular_substract (int x, int y) constexpr
Definition at line 27 of file modular_arithmetic.hpp.
     {
         auto a = static_cast<std::int64_t>(x);
         auto b = static_cast<std::int64_t>(y);
         auto c = (a - b);
         c = c % MODULO;
         c = (c + MODULO) % MODULO;
         return static_cast<int>(c);
     }
References MODULO.
new_binary_tree()
TreeNode* hsc_snippets::new_binary_tree (const std::vector< std::optional< int >> v)
Constructs a binary tree from a vector of optional integers.
Parameters
v A vector of std::optional<int>, where each element represents a potential node in the binary tree. An std::nullopt value indicates the absence of a node at that position.
Returns
A pointer to the root node of the newly constructed binary tree. Returns nullptr if the input vector is empty.
Definition at line 31 of file binary_tree.hpp.
     {
         if (v.empty())
         {
             return nullptr;
         }
         const auto n = v.size();
         assert(v[0].has_value());
         auto root = new TreeNode(v[0].value());
         auto q = std::queue<TreeNode *>{};
         q.push(root);
         int i = 1;
         while (i < n)
         {
             auto node = q.front();
             q.pop();
             if (v[i].has_value())
             {
                 node->left = new TreeNode(v[i].value());
                 q.push(node->left);
             }
             i += 1;
             if (i >= n)
             {
                 break;
             }
             if (v[i].has_value())
             {
                 node->right = new TreeNode(v[i].value());
                 q.push(node->right);
             }
             i += 1;
         }
         return root;
     }
nextGreaterElement()
template<typename T > std::vector<T> hsc_snippets::nextGreaterElement (const std::vector< T > & nums, std::function< T()> no_greater)
Finds the next greater element for each element in a sequence.
Template Parameters
T The type of elements in the sequence.
Parameters
nums The sequence of elements.
no_greater Function to call when no greater element is found.
Returns
A vector containing the next greater element for each element in nums.
Definition at line 77 of file monotonic_stack.hpp.
     {
         std::vector<T> result{};
         result.reserve(nums.size());
         MonotonicDecreasingStack<T> decreasingStack;
         for (auto num : nums)
         {
             auto tmp = decreasingStack.push(num);
             if (!tmp.has_value())
             {
                 result.push_back(no_greater());
             }
             else
             {
                 result.push_back(tmp.value());
             }
         }
         return result;
     }
References hsc_snippets::MonotonicStack< T, Comparator >::push().
numBits()
template<std::integral T> int hsc_snippets::numBits (T num)
Calculates the number of bits required to represent an integer in binary. For negative numbers, it returns the number of bits in the type (e.g., 32 for int), assuming two's complement representation.
Template Parameters
T The type of the input number, constrained to integral types.
Parameters
num The input number whose binary bit count is to be calculated.
Returns
The number of bits required to represent num in binary, or the bit size of T for negative numbers.
Definition at line 39 of file number_utils.hpp.
     {
         if (num < 0)
         {
             return sizeof(T) << 3;
         }
         int cnt = 0;
         while (num != 0)
         {
             cnt += 1;
             num = num >> 1;
         }
         return cnt;
     }
numDigits()
template<std::integral T> int hsc_snippets::numDigits (T num)
Calculates the number of digits in the decimal representation of an integer.
Template Parameters
T The type of the input number, constrained to integral types.
Parameters
num The input number whose number of decimal digits is to be calculated.
Returns
The number of digits in the decimal representation of num.
Definition at line 18 of file number_utils.hpp.
     {
         int cnt = 0;
         while (num != 0)
         {
             cnt += 1;
             num /= 10;
         }
         return cnt;
     }
numOfGreaterElements()
template<std::totally_ordered T> int hsc_snippets::numOfGreaterElements (const std::vector< T > & v, T value)
Definition at line 10 of file sorted_utils.hpp.
     {
         auto it = std::lower_bound(v.cbegin(), v.cend(), value, [](const T &value, const T &element)
                                    { return value <= element; });
         if (it == v.cend())
         {
             return 0;
         }
         return v.cend() - it;
     }
operator<() [1/3]
template<std::integral T> static bool hsc_snippets::operator< (const _Interval< T > & interval, T x) static
Definition at line 36 of file interval_map.hpp.
     {
         return interval.right <= x;
     }
References hsc_snippets::_Interval< T >::right.
operator<() [2/3]
template<std::integral T> static bool hsc_snippets::operator< (const _Interval< T > & interval1, const _Interval< T > & interval2) static
Definition at line 47 of file interval_map.hpp.
     {
         return interval1.left < interval2.left;
     }
References hsc_snippets::_Interval< T >::left.
operator<() [3/3]
template<std::integral T> static bool hsc_snippets::operator< (T x, const _Interval< T > & interval) static
Definition at line 41 of file interval_map.hpp.
     {
         return x < interval.left;
     }
References hsc_snippets::_Interval< T >::left.
postorder()
void hsc_snippets::postorder (TreeNode * root, std::function< void(int)> func)
Post-order traversal of a binary tree.
Parameters
root Root node of the binary tree.
func Function to process each node's value.
Definition at line 138 of file binary_tree.hpp.
     {
         if (root == nullptr)
             return;
         postorder(root->left, func);
         postorder(root->right, func);
         func(root->val);
     }
References hsc_snippets::TreeNode::left, hsc_snippets::TreeNode::right, and hsc_snippets::TreeNode::val.
preorder()
void hsc_snippets::preorder (TreeNode * root, std::function< void(int)> func)
Pre-order traversal of a binary tree.
Parameters
root Root node of the binary tree.
func Function to process each node's value.
Definition at line 124 of file binary_tree.hpp.
     {
         if (root == nullptr)
             return;
         func(root->val);
         preorder(root->left, func);
         preorder(root->right, func);
     }
References hsc_snippets::TreeNode::left, hsc_snippets::TreeNode::right, and hsc_snippets::TreeNode::val.
SieveOfEratosthenes()
std::vector<int> hsc_snippets::SieveOfEratosthenes (int n)
Implements the Sieve of Eratosthenes algorithm to find all prime numbers up to a given limit n.
Parameters
n The upper limit (inclusive) up to which prime numbers are to be found.
Returns
A std::vector<int> containing all the prime numbers less than or equal to n.
Definition at line 95 of file number_utils.hpp.
     {
         // Initialize a boolean vector "prime" with entries up to n. All entries are initially set to true.
         // A value in prime[i] will be false if i is not a prime number, and true if it is a prime number.
         std::vector<bool> prime(n + 1, true);
         prime[0] = prime[1] = false; // 0 and 1 are not considered prime numbers.
         // This vector will store all the prime numbers found.
         std::vector<int> primes;
         // Start iterating from the first prime number, 2, up to the square root of n.
         // We only need to go up to sqrt(n) because if n has a divisor greater than sqrt(n),
         // it must also have a smaller one, so all composites will have been marked by this point.
         for (int p = 2; p <= std::sqrt(n); ++p)
         {
             // If prime[p] is true, then it is a prime number.
             if (prime[p])
             {
                 // Mark all multiples of p starting from p^2 as not prime.
                 // Starting from p^2 because all smaller multiples of p would have already been marked by smaller primes.
                 for (int i = p * p; i <= n; i += p)
                 {
                     prime[i] = false;
                 }
             }
         }
         // Collect all prime numbers: iterate over the range up to n and
         // add the number to the primes list if its corresponding value in the prime vector is true.
         for (int p = 2; p <= n; ++p)
         {
             if (prime[p])
             {
                 primes.push_back(p);
             }
         }
         // Return the vector containing all the primes found.
         return primes;
     }
smallest_index()
template<typename T , std::integral I = int> I hsc_snippets::smallest_index (I low, I high, const T & value, auto && func)
Finds the smallest index in a non-decreasing array where the function applied to the index returns a value greater than or equal to the specified value.
Template Parameters
T The type of the value against which the function's results are compared.
I The integral type of the index, defaulting to int.
Parameters
low The lower bound of the search range (inclusive).
high The upper bound of the search range (inclusive).
value The value to compare against the function's results.
func The function to apply to each index, expected to return non-decreasing values for the range [low, high].
Returns
The smallest index for which func(index) >= value, or -1 if no such index exists.
Definition at line 119 of file sorted_utils.hpp.
     {
         I ans = -1; // Initialize answer to -1 to indicate no valid index found yet
         while (low <= high)
         {
             I mid = low + (high - low) / 2; // Calculate the mid-point of the current search range
             T res = func(mid);              // Evaluate the function at the mid-point
             if (res >= value)
             {
                 ans = mid;      // Update answer since res is greater than or equal to value
                 high = mid - 1; // Narrow the search to the left half to find the smallest index
             }
             else
             {
                 low = mid + 1; // Narrow the search to the right half since res is less than value
             }
         }
         return ans; // Return the found index or -1 if no such index exists
     }
sortThree()
template<std::integral T> void hsc_snippets::sortThree (T & a, T & b, T & c)
Sorts three elements in non-decreasing order using a simple comparison and swap algorithm.
Template Parameters
T The type of the elements to be sorted. Must be an integral type.
Parameters
a Reference to the first element, will be the smallest after sorting.
b Reference to the second element, will be the middle element after sorting.
c Reference to the third element, will be the largest after sorting.
Definition at line 149 of file sorted_utils.hpp.
     {
         if (a > b)
         {
             std::swap(a, b);
         }
         if (b > c)
         {
             std::swap(b, c);
         }
         if (a > b)
         {
             std::swap(a, b);
         }
     }
sum() [1/2]
template<numeric T> T hsc_snippets::sum (T x)
Definition at line 64 of file varadic_numeric.hpp.
     {
         return x;
     }
Referenced by hsc_snippets::SegmentTree< T >::_range_sum(), and sum().
sum() [2/2]
template<numeric T, numeric... Args> T hsc_snippets::sum (T x, Args... args)
Definition at line 69 of file varadic_numeric.hpp.
     {
         return x + sum(args...);
     }
References sum().
to_string() [1/3]
std::string hsc_snippets::to_string (const std::vector< std::string > & vec)
Convert a vector of strings to its string representation, with elements separated by commas. The resulting string is enclosed in square brackets.
Parameters
vec The vector of strings to convert. Each element in the vector is expected to be a string.
Returns
A string that represents the vector's contents, formatted as "[element1, element2, ...]". If the vector is empty, the returned string will be "[]".
Definition at line 143 of file string_utils.hpp.
     {
         std::stringstream ss;
         ss << "[";
         for (size_t i = 0; i < vec.size(); ++i)
         {
             ss << vec[i];
             if (i < vec.size() - 1)
             { // Check if it's not the last element
                 ss << ", ";
             }
         }
         ss << "]";
         return ss.str();
     }
to_string() [2/3]
template<std::integral T> std::string hsc_snippets::to_string (const std::vector< std::vector< T >> & vec)
Convert a vector of vectors of integral type T to its string representation.
Template Parameters
T The integral type of elements in the vectors.
Parameters
vec The vector of vectors to convert.
Returns
The string representation of the vector of vectors.
Definition at line 167 of file string_utils.hpp.
     {
         std::stringstream ss;
         ss << "[";
         for (size_t i = 0; i < vec.size(); ++i)
         {
             ss << to_string(vec[i]);
             if (i < vec.size() - 1)
             { // Check if it's not the last element
                 ss << ", ";
             }
         }
         ss << "]";
         return ss.str();
     }
References to_string().
to_string() [3/3]
template<std::integral T> std::string hsc_snippets::to_string (const std::vector< T > & vec)
Convert a vector of integral type T to its string representation.
Template Parameters
T The integral type of elements in the vector.
Parameters
vec The vector to convert.
Returns
The string representation of the vector.
Definition at line 119 of file string_utils.hpp.
     {
         std::stringstream ss;
         ss << "[";
         for (size_t i = 0; i < vec.size(); ++i)
         {
             ss << vec[i];
             if (i < vec.size() - 1)
             { // Check if it's not the last element
                 ss << ", ";
             }
         }
         ss << "]";
         return ss.str();
     }
Referenced by to_string().
Variable Documentation
MODULO
constexpr int hsc_snippets::MODULO = static_cast<int>(1e9 + 7) static constexpr
Definition at line 10 of file modular_arithmetic.hpp.
Referenced by additive_inverse(), modular_add(), modular_cube(), modular_multiply(), modular_pow2(), modular_square(), and modular_substract().
numeric
template<typename T > concept hsc_snippets::numeric = std::integral<T> || std::floating_point<T>
Definition at line 9 of file varadic_numeric.hpp.