name: Tests
on:
  push:
    branches:
      - main
    paths-ignore:
      - '*.md'
  pull_request:
    branches:
      - main

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Checkout submodules
        run: git submodule update --init --recursive

      - name: Build
        run: |
          mkdir -p build
          cd build
          cmake .. 
          cmake --build . --config Release

      - name: Test
        run: |
          cd build
          ctest -v -C Release
